/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bantizleme;

import javax.swing.*;
import bantizleme.destek.islevseller;
import bantizleme.destek.baglanti;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author CI
 */
public class kurtarma extends javax.swing.JFrame {

    /**
     * Creates new form kurtarma
     *
     * @param e
     */
    public kurtarma(Exception e) {
        initComponents();
        hataMesaji.setText(e.getMessage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel18 = new javax.swing.JPanel();
        dbKullaniciTxtField = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        dbBaglantiYoluTxtField = new javax.swing.JTextField();
        dbSifreTxtField = new javax.swing.JPasswordField();
        baglantiYoluSecBtn = new javax.swing.JButton();
        genelAyarlaBtn = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        ePostaAdresiTxtField = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        ePostaSifreTxtField = new javax.swing.JPasswordField();
        jLabel48 = new javax.swing.JLabel();
        ePostaKullaniciAdiTxtField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        hataMesaji = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kurtarma Ekranı");

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GENEL AYARLAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText(" Veri Tabanı Kullanıcı Adı");
        jLabel36.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("Veri Tabanı Kullanıcı Şifresi");
        jLabel37.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("Bağlantı Yolu");
        jLabel38.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        dbBaglantiYoluTxtField.setEditable(false);

        dbSifreTxtField.setText("jPasswordField1");

        baglantiYoluSecBtn.setText("...");
        baglantiYoluSecBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baglantiYoluSecBtnActionPerformed(evt);
            }
        });

        genelAyarlaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/ayarla.png"))); // NOI18N
        genelAyarlaBtn.setText("AYARLA");
        genelAyarlaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genelAyarlaBtnActionPerformed(evt);
            }
        });

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel45.setText("E-posta Adresi");
        jLabel45.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel46.setText("E-posta Kullanıcı Şifresi");
        jLabel46.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        ePostaSifreTxtField.setText("jPasswordField1");

        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel48.setText("E-posta Kullanıcı Adı");
        jLabel48.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ePostaKullaniciAdiTxtField)
                    .addComponent(dbKullaniciTxtField)
                    .addComponent(dbBaglantiYoluTxtField)
                    .addComponent(dbSifreTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addComponent(ePostaAdresiTxtField)
                    .addComponent(ePostaSifreTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(baglantiYoluSecBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(genelAyarlaBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(dbBaglantiYoluTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baglantiYoluSecBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(dbKullaniciTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(dbSifreTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(ePostaKullaniciAdiTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(ePostaAdresiTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(ePostaSifreTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(genelAyarlaBtn))
        );

        hataMesaji.setColumns(20);
        hataMesaji.setRows(5);
        jScrollPane1.setViewportView(hataMesaji);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(247, 247, 247))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baglantiYoluSecBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baglantiYoluSecBtnActionPerformed
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        final JFrame baglantiYolu = new JFrame("Bağlantı Yolu Belirleme");
        baglantiYolu.setLayout(new GridLayout(3, 3));
        JLabel surucuEtiketi = new JLabel("Sürücü Adı");
        JLabel sunucuEtiketi = new JLabel("Sunucu ve Port");
        JLabel dbAdiEtiketi = new JLabel("Veri Tabanı Adı");
        JLabel surucu = new JLabel("jdbc:mysql://");
        final JTextField sunucu = new JTextField();
        final JTextField dbAdi = new JTextField();
        dbAdi.setToolTipText("ornek.com veya 127.0.0.1:80 şeklinde yazılır.");

        baglantiYolu.setResizable(false);
        baglantiYolu.add(surucuEtiketi);

        baglantiYolu.add(sunucuEtiketi);
        baglantiYolu.add(dbAdiEtiketi);
        baglantiYolu.add(surucu);
        baglantiYolu.add(sunucu);
        baglantiYolu.add(dbAdi);
        JButton kabulBtn = new JButton("KABUL");

        kabulBtn.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                dbBaglantiYoluTxtField.setText("jdbc:mysql://" + sunucu.getText() + "/" + dbAdi.getText());
                baglantiYolu.dispose();
            }
        });
        baglantiYolu.add(new JLabel());
        baglantiYolu.add(kabulBtn);
        baglantiYolu.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        baglantiYolu.setBounds(baglantiYoluSecBtn.getX() - 40, baglantiYoluSecBtn.getY() + 30, 370, 100);
        baglantiYolu.setVisible(true);
    }//GEN-LAST:event_baglantiYoluSecBtnActionPerformed

    private void genelAyarlaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genelAyarlaBtnActionPerformed
        try {
            islevseller islevAnahtar = new islevseller();
            islevAnahtar.ayarla("baglanti", dbBaglantiYoluTxtField.getText());
            islevAnahtar.ayarla("kullanici", dbKullaniciTxtField.getText());
            islevAnahtar.ayarla("parola", dbSifreTxtField.getText());
            baglanti bagAnahtar = new baglanti();
            com.mysql.jdbc.Connection con = bagAnahtar.ac();
            Statement st = con.createStatement();
            st.execute("DELETE FROM mail_listesi WHERE aktifKullanici='1'");
            st.execute("INSERT INTO mail_listesi(mailSahibi, mailAdresi, sifre, aktifKullanici) VALUES('"
                    + ePostaKullaniciAdiTxtField.getText() + "','"
                    + ePostaAdresiTxtField.getText() + "','" + ePostaSifreTxtField.getText() + "','1')");

        } catch (SQLException ex) {
            //kutuk kutukAnahtar=new kutuk();
            Logger.getLogger(veriGirisi.class.getName()).log(Level.SEVERE, null, ex);
            //kutukAnahtar.kutukTut("YAKALANAN İSTİSNA : "+ex,Level.SEVERE);
        }
    }//GEN-LAST:event_genelAyarlaBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baglantiYoluSecBtn;
    private javax.swing.JTextField dbBaglantiYoluTxtField;
    private javax.swing.JTextField dbKullaniciTxtField;
    private javax.swing.JPasswordField dbSifreTxtField;
    private javax.swing.JTextField ePostaAdresiTxtField;
    private javax.swing.JTextField ePostaKullaniciAdiTxtField;
    private javax.swing.JPasswordField ePostaSifreTxtField;
    private javax.swing.JButton genelAyarlaBtn;
    private javax.swing.JTextArea hataMesaji;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
